### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by tajemouti** [tajemouti/ruby-group-capstone#27]
## Hi Reviewer 👋 ##

This issue is created to provide task assignments and team information for [Ruby group capstone](https://github.com/tajemouti/ruby-group-capstone/projects/1) project.

We have a team of 3 working on this project:

Team member #1: [Kaiserabbas](https://github.com/Kaiserabbas)
Team member #2: [tajemouti](https://github.com/tajemouti)
Team member #3: [MozamelJawad](https://github.com/MozamelJawad)

**Comment by danmainah** [comment]
Hi @MozamelJawad , @Kaiserabbas and @tajemouti , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Created a new kanban board based on [ TEMPLATE](https://github.com/microverseinc/curriculum-ruby/projects/1) board given.
✔️  Added tasks for all the users and ensured all tasks have a title description and is assigned to a member.


# Required Changes ♻️

- [ ] @Team Great work adding the group tasks on your Kanban board, however you forgot to add the task below
![image](https://github.com/tajemouti/ruby-group-capstone/assets/61408860/fe8aa6c4-105c-413c-a88e-a36f5f0d6054)
![image](https://github.com/tajemouti/ruby-group-capstone/assets/61408860/8d81e0a6-ef2e-45b2-8c8e-4bc98d3929a4)

- [ ] @Team Great work adding tasks for team members, however according to the project description each task should be in its own card, kindly separate the properties for different classes.
![image](https://github.com/tajemouti/ruby-group-capstone/assets/61408860/e5970898-d651-4910-a0fc-e468be4bc2c9)
![image](https://github.com/tajemouti/ruby-group-capstone/assets/61408860/4db242d5-1a51-4b6b-ad16-ff40ad9dbeda)
![image](https://github.com/tajemouti/ruby-group-capstone/assets/61408860/b37e5258-826f-43e9-91a0-70e9d51800a5)
![image](https://github.com/tajemouti/ruby-group-capstone/assets/61408860/0ecc1c4a-2b89-438a-b48e-adaf14917c0c)

- [ ] @Team Great work adding tasks for team members, however, you didn't include all that needs to be implemented for these tasks, kindly consider editing your title and description to match the project requirement, for the tasks
![image](https://github.com/tajemouti/ruby-group-capstone/assets/61408860/e419f532-ec70-429a-b8a8-f5f74ae2a80d)
![image](https://github.com/tajemouti/ruby-group-capstone/assets/61408860/c97fac2c-7b8b-408e-8978-2a8ab04187bb)
![image](https://github.com/tajemouti/ruby-group-capstone/assets/61408860/94da5c13-a889-4b15-8e78-29b73db80b6f)

![image](https://github.com/tajemouti/ruby-group-capstone/assets/61408860/89848ee0-bffd-4ab9-b570-a47be83baf26)

- [ ] @Team Great work adding the  tasks for team members on your Kanban board, however you forgot to add the task below
![image](https://github.com/tajemouti/ruby-group-capstone/assets/61408860/54f41e4c-2507-4238-bb3d-0ebd74dbd57e)
![image](https://github.com/tajemouti/ruby-group-capstone/assets/61408860/9f240e42-ed8b-44b3-9ace-8b4bbdabca9d)
![image](https://github.com/tajemouti/ruby-group-capstone/assets/61408860/0de002c4-38c7-4aa3-91e4-f060e69d79c1)



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by tajemouti** [comment]
Hello @danmainah,
Thank you for this insightful feedback.
Cheers

**Comment by iambenkis** [comment]
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

-  A description for the unit test task has been added :heavy_check_mark: 
- Each  task is in its own card ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @iambenkis in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
